/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Trips */
        get: operations["search_trips_api_v1_planner_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip Detail */
        get: operations["get_trip_detail_api_v1_planner_trips__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/trips/{trip_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Trip */
        post: operations["start_trip_api_v1_planner_trips__trip_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/trips/{trip_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance Trip */
        post: operations["advance_trip_api_v1_planner_trips__trip_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stops */
        get: operations["list_stops_api_v1_stops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stop */
        get: operations["get_stop_api_v1_stops__stop_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arrivals/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home Arrivals */
        get: operations["get_home_arrivals_api_v1_arrivals_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arrivals/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stop Arrivals */
        get: operations["get_stop_arrivals_api_v1_arrivals_stops__stop_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alerts */
        get: operations["get_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Report */
        post: operations["submit_report_api_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Stats */
        get: operations["get_my_stats_api_v1_users_me_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveTripOut */
        ActiveTripOut: {
            /** Tripid */
            tripId: string;
            /** Activetripid */
            activeTripId: string;
            /** Currentstepindex */
            currentStepIndex: number;
            /** Steps */
            steps: (components["schemas"]["WalkStepOut"] | components["schemas"]["BusStepOut"] | components["schemas"]["TransferStepOut"])[];
            /** Etaminutes */
            etaMinutes: number;
            /** Started */
            started: number;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "bad" | "warn" | "ok";
            /** Titlekey */
            titleKey: string;
            /** Bodykey */
            bodyKey: string;
            /** Emittedat */
            emittedAt: string;
            /** Routes */
            routes: string[];
        };
        /** ArrivalOut */
        ArrivalOut: {
            /** Id */
            id: string;
            /** Route */
            route: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "bus" | "train";
            /** Destes */
            destEs: string;
            /** Desten */
            destEn: string;
            /** Etasec */
            etaSec: number;
            /** Status */
            status: string;
            /** Occupancy */
            occupancy: number;
            /** Note Es */
            note_es?: string | null;
            /** Note En */
            note_en?: string | null;
        };
        /** BusStepOut */
        BusStepOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "bus";
            /** Route */
            route: string;
            /** Minutes */
            minutes: number;
            /** Fromes */
            fromEs: string;
            /** Fromen */
            fromEn: string;
            /** Toes */
            toEs: string;
            /** Toen */
            toEn: string;
            /** Time */
            time: string;
            /** Occ */
            occ: number;
            /** Stops */
            stops: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Displayname */
            displayName: string;
        };
        /** ReportCreatedOut */
        ReportCreatedOut: {
            /** Id */
            id: number;
            /** Userid */
            userId: string | null;
            /** Routeid */
            routeId: string | null;
            /** Stopid */
            stopId: string | null;
            /** Type */
            type: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Createdat */
            createdAt: string;
        };
        /** ReportSubmitIn */
        ReportSubmitIn: {
            /** Type */
            type: string;
            /** Routeid */
            routeId?: string | null;
            /** Stopid */
            stopId?: string | null;
            /** Description */
            description: string;
        };
        /**
         * SortMode
         * @enum {string}
         */
        SortMode: "fastest" | "cheapest" | "fewest";
        /** StopDetailOut */
        StopDetailOut: {
            stop: components["schemas"]["StopOut"];
            /** Arrivals */
            arrivals: components["schemas"]["ArrivalOut"][];
            /** Updatedat */
            updatedAt: number;
        };
        /** StopOut */
        StopOut: {
            /** Id */
            id: string;
            /** Namekey */
            nameKey: string;
            /** Addrkey */
            addrKey: string;
            /** Dist */
            dist: number;
            /** Live */
            live: boolean;
            /** Routes */
            routes: string[];
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** TokenOut */
        TokenOut: {
            /** Accesstoken */
            accessToken: string;
            /** Expiresat */
            expiresAt: string;
        };
        /** TransferStepOut */
        TransferStepOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "transfer";
            /** Minutes */
            minutes: number;
            /** Toes */
            toEs: string;
            /** Toen */
            toEn: string;
            /** Time */
            time: string;
        };
        /** TripAdvanceIn */
        TripAdvanceIn: {
            /** Currentstepindex */
            currentStepIndex: number;
            /** Activetripid */
            activeTripId?: string | null;
        };
        /** TripDetailOut */
        TripDetailOut: {
            /** Id */
            id: string;
            /** Minutes */
            minutes: number;
            /** Price */
            price: number;
            /** Transfers */
            transfers: number;
            /** Walkmin */
            walkMin: number;
            /** Leavein */
            leaveIn: number;
            /** Confidence */
            confidence: number;
            /** Occupancy */
            occupancy: number;
            /** Steps */
            steps: (components["schemas"]["WalkStepOut"] | components["schemas"]["BusStepOut"] | components["schemas"]["TransferStepOut"])[];
        };
        /** TripOptionOut */
        TripOptionOut: {
            /** Id */
            id: string;
            /** Tag */
            tag: string;
            /** Minutes */
            minutes: number;
            /** Price */
            price: number;
            /** Transfers */
            transfers: number;
            /** Walkmin */
            walkMin: number;
            /** Leavein */
            leaveIn: number;
            /** Confidence */
            confidence: number;
            /** Occupancy */
            occupancy: number;
            /** Steps */
            steps: (components["schemas"]["WalkStepOut"] | components["schemas"]["BusStepOut"] | components["schemas"]["TransferStepOut"])[];
        };
        /** UserProfileOut */
        UserProfileOut: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Displayname */
            displayName: string;
            /** Reputationscore */
            reputationScore: number;
            /** Createdat */
            createdAt: string;
        };
        /** UserStatsOut */
        UserStatsOut: {
            /** Trips */
            trips: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WalkStepOut */
        WalkStepOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "walk";
            /** Minutes */
            minutes: number;
            /** Toes */
            toEs: string;
            /** Toen */
            toEn: string;
            /** Time */
            time: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_trips_api_v1_planner_search_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                sort?: components["schemas"]["SortMode"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripOptionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_detail_api_v1_planner_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_trip_api_v1_planner_trips__trip_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveTripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_trip_api_v1_planner_trips__trip_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripAdvanceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveTripOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stops_api_v1_stops_get: {
        parameters: {
            query?: {
                lat?: number | null;
                lng?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stop_api_v1_stops__stop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_arrivals_api_v1_arrivals_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrivalOut"][];
                };
            };
        };
    };
    get_stop_arrivals_api_v1_arrivals_stops__stop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArrivalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                routeIds?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_report_api_v1_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportSubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileOut"];
                };
            };
        };
    };
    get_my_stats_api_v1_users_me_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsOut"];
                };
            };
        };
    };
}
